export const sourceTypeValues = [
  "company_homepage",
  "about_page",
  "product_page",
  "solutions_page",
  "pricing_page",
  "customer_page",
  "security_page",
  "privacy_page",
  "docs_page",
  "developer_page",
  "careers_page",
  "blog_page",
  "newsroom_page",
  "investor_relations_page",
  "investor_report",
  "earnings_release",
  "company_social_profile",
  "executive_social_profile",
  "status_page",
  "incident_page",
  "support_page",
  "changelog_page",
  "news_article",
  "review_platform",
  "complaint_forum",
  "competitor_page",
  "market_analysis",
  "pdf_document",
  "company_site",
  "other",
] as const;

export type SourceType = (typeof sourceTypeValues)[number];
